import { describe, it, expect, vi } from 'vitest'

import worker, { buildPrompt } from '../brochure-ai-writer.js'

function mockEnv(overrides = {}) {
  const kvStore = new Map()
  return {
    ENVIRONMENT: 'production',
    AI: { run: vi.fn().mockResolvedValue({ response: 'A heartfelt tribute generated by AI.' }) },
    RATE_LIMITS: {
      get: async (k) => kvStore.get(k) ?? null,
      put: async (k, v, _opts) => { kvStore.set(k, v) },
    },
    _kv: kvStore,
    ...overrides,
  }
}

function makePostReq(body, headers = {}) {
  return new Request('https://ai-writer.example.com/', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'CF-Connecting-IP': '1.2.3.4',
      'Origin': 'https://funeralpress.org',
      ...headers,
    },
    body: JSON.stringify(body),
  })
}

function makeGetReq(path, headers = {}) {
  return new Request(`https://ai-writer.example.com${path}`, {
    method: 'GET',
    headers: {
      'CF-Connecting-IP': '1.2.3.4',
      'Origin': 'https://funeralpress.org',
      ...headers,
    },
  })
}

describe('buildPrompt', () => {
  it('tribute prompt includes deceased name, relationship, memories, and tone', () => {
    const out = buildPrompt('tribute', {
      deceasedName: 'Kwame Nkrumah',
      relationship: 'son',
      memories: 'wise, generous, devoted father',
      tone: 'reverent and joyful',
    })
    expect(out).toContain('Kwame Nkrumah')
    expect(out).toContain('son')
    expect(out).toContain('wise, generous, devoted father')
    expect(out).toContain('reverent and joyful')
  })

  it('biography prompt includes deceased name and life details', () => {
    const out = buildPrompt('biography', {
      deceasedName: 'Ama Serwaa',
      memories: 'born in Kumasi, taught for 40 years, raised five children',
    })
    expect(out).toContain('Ama Serwaa')
    expect(out).toContain('born in Kumasi, taught for 40 years, raised five children')
  })

  it('acknowledgements prompt includes the family name field', () => {
    const out = buildPrompt('acknowledgements', {
      name: 'The Mensah Family',
      deceasedName: 'Yaw Mensah',
    })
    expect(out).toContain('The Mensah Family')
    expect(out).toContain('Yaw Mensah')
  })

  it('unknown type returns a generic fallback prompt (graceful)', () => {
    const out = buildPrompt('not-a-real-mode', { deceasedName: 'Test' })
    // The worker returns a generic non-empty fallback string for unknown types.
    expect(typeof out).toBe('string')
    expect(out.length).toBeGreaterThan(0)
    expect(out).toContain('funeral brochure')
  })
})

describe('POST / (legacy single-type mode)', () => {
  it('returns 200 with { text } on happy path for tribute', async () => {
    const env = mockEnv()
    const res = await worker.fetch(
      makePostReq({
        type: 'tribute',
        deceasedName: 'Kwame Nkrumah',
        relationship: 'son',
        memories: 'wise and kind',
        tone: 'warm',
      }),
      env
    )
    expect(res.status).toBe(200)
    const body = await res.json()
    expect(body.text).toBe('A heartfelt tribute generated by AI.')
    expect(env.AI.run).toHaveBeenCalledTimes(1)
    expect(env.AI.run).toHaveBeenCalledWith(
      '@cf/meta/llama-3.1-8b-instruct',
      expect.objectContaining({ messages: expect.any(Array) })
    )
  })

  it('returns 400 when type is missing', async () => {
    const env = mockEnv()
    const res = await worker.fetch(
      makePostReq({ deceasedName: 'No type', memories: 'test' }),
      env
    )
    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toMatch(/Invalid type/i)
    expect(env.AI.run).not.toHaveBeenCalled()
  })

  it('returns 400 when type is invalid (acts as missing-required-fields guard)', async () => {
    const env = mockEnv()
    const res = await worker.fetch(
      makePostReq({ type: 'not-a-real-type' }),
      env
    )
    expect(res.status).toBe(400)
    const body = await res.json()
    expect(body.error).toMatch(/Invalid type/i)
  })

  it('returns 500 with error JSON when env.AI.run throws (no unhandled exception)', async () => {
    const env = mockEnv({
      AI: { run: vi.fn().mockRejectedValue(new Error('AI binding failed')) },
    })
    const res = await worker.fetch(
      makePostReq({ type: 'tribute', deceasedName: 'X', memories: 'y' }),
      env
    )
    expect(res.status).toBe(500)
    const body = await res.json()
    expect(body.error).toBe('AI binding failed')
  })

  it('returns 500 when AI returns malformed/empty response', async () => {
    const env = mockEnv({
      AI: { run: vi.fn().mockResolvedValue({}) }, // no .response field
    })
    const res = await worker.fetch(
      makePostReq({ type: 'tribute', deceasedName: 'X', memories: 'y' }),
      env
    )
    expect(res.status).toBe(500)
    const body = await res.json()
    expect(body.error).toMatch(/no response/i)
  })
})

describe('rate limiting', () => {
  it('returns 429 once rate-limit counter is at the cap (5)', async () => {
    const env = mockEnv()
    // Seed the rate-limit key to the cap so the next request is rejected.
    await env.RATE_LIMITS.put('rate:1.2.3.4:ai-writer', '5')
    const res = await worker.fetch(
      makePostReq({ type: 'tribute', deceasedName: 'X', memories: 'y' }),
      env
    )
    expect(res.status).toBe(429)
    expect(env.AI.run).not.toHaveBeenCalled()
  })
})

describe('GET /health', () => {
  it('returns 200 with status ok and service name', async () => {
    const env = mockEnv()
    const res = await worker.fetch(makeGetReq('/health'), env)
    expect(res.status).toBe(200)
    const body = await res.json()
    expect(body.status).toBe('ok')
    expect(body.service).toBe('ai-writer')
  })
})
