export const invitationThemes = {
  burgundyGold: {
    name: 'Burgundy & Gold',
    description: 'Rich burgundy with ornate gold accents',
    layout: 'ornate',
    headerBg: '#5C1A2A',
    bodyBg: '#4A1525',
    accent: '#D4AF37',
    detailsBg: '#FDF8F0',
    detailsText: '#2A1015',
    footerBg: '#5C1A2A',
    headerText: '#FFFFFF',
    nameText: '#D4AF37',
    bodyText: '#F0E0D0',
    divider: '#D4AF37',
    badgeBg: '#D4AF37',
    badgeText: '#5C1A2A',
    eventCardBg: 'rgba(212,175,55,0.08)',
    eventCardBorder: '#D4AF37',
  },
  midnightGold: {
    name: 'Midnight & Gold',
    description: 'Dramatic black with gold flourishes',
    layout: 'ornate',
    headerBg: '#0A0A0A',
    bodyBg: '#111111',
    accent: '#C9A84C',
    detailsBg: '#1A1A1A',
    detailsText: '#E0E0E0',
    footerBg: '#0A0A0A',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#E0E0E0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#0A0A0A',
    eventCardBg: 'rgba(201,168,76,0.1)',
    eventCardBorder: '#C9A84C',
  },
  ivoryClassic: {
    name: 'Ivory Classic',
    description: 'Light, elegant ivory with warm charcoal',
    layout: 'centered',
    headerBg: '#FFFFFF',
    bodyBg: '#FAF8F5',
    accent: '#8B7340',
    detailsBg: '#FFFFFF',
    detailsText: '#1A1A1A',
    footerBg: '#2A2520',
    headerText: '#2A2520',
    nameText: '#8B7340',
    bodyText: '#3A3530',
    divider: '#8B7340',
    badgeBg: '#2A2520',
    badgeText: '#FAF8F5',
    eventCardBg: '#F5F2ED',
    eventCardBorder: '#8B7340',
  },
  rosePetal: {
    name: 'Rose Petal',
    description: 'Soft, tender rose and blush tones',
    layout: 'centered',
    headerBg: '#3A1020',
    bodyBg: '#4A1828',
    accent: '#D4A0A8',
    detailsBg: '#FDF0F2',
    detailsText: '#3A1020',
    footerBg: '#3A1020',
    headerText: '#FFFFFF',
    nameText: '#D4A0A8',
    bodyText: '#F8E0E5',
    divider: '#D4A0A8',
    badgeBg: '#D4A0A8',
    badgeText: '#3A1020',
    eventCardBg: 'rgba(212,160,168,0.1)',
    eventCardBorder: '#D4A0A8',
  },
  royalNavy: {
    name: 'Royal Navy',
    description: 'Deep navy blue with golden highlights',
    layout: 'split',
    headerBg: '#0E1E38',
    bodyBg: '#0A1628',
    accent: '#C9A84C',
    detailsBg: '#F0F5F8',
    detailsText: '#0A1628',
    footerBg: '#0E1E38',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#D8E8F0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#0A1628',
    eventCardBg: 'rgba(201,168,76,0.08)',
    eventCardBorder: '#C9A84C',
  },
  emeraldGold: {
    name: 'Emerald & Gold',
    description: 'Lush emerald green with warm gold',
    layout: 'split',
    headerBg: '#0D2818',
    bodyBg: '#0A2015',
    accent: '#C9A84C',
    detailsBg: '#F0F5F0',
    detailsText: '#0D2818',
    footerBg: '#0D2818',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#D0E8D0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#0D2818',
    eventCardBg: 'rgba(201,168,76,0.08)',
    eventCardBorder: '#C9A84C',
  },
  purpleMajesty: {
    name: 'Purple Majesty',
    description: 'Regal purple with silver accents',
    layout: 'bordered',
    headerBg: '#1E0A38',
    bodyBg: '#28104A',
    accent: '#C0C0C8',
    detailsBg: '#F5F0FA',
    detailsText: '#1E0A38',
    footerBg: '#1E0A38',
    headerText: '#FFFFFF',
    nameText: '#C0C0C8',
    bodyText: '#E8E0F0',
    divider: '#C0C0C8',
    badgeBg: '#C0C0C8',
    badgeText: '#1E0A38',
    eventCardBg: 'rgba(192,192,200,0.1)',
    eventCardBorder: '#C0C0C8',
  },
  creamLinen: {
    name: 'Cream Linen',
    description: 'Warm cream with chocolate brown accents',
    layout: 'bordered',
    headerBg: '#2E1A0E',
    bodyBg: '#3A2418',
    accent: '#D4AF60',
    detailsBg: '#FDF8F0',
    detailsText: '#2E1A0E',
    footerBg: '#2E1A0E',
    headerText: '#FDF8F0',
    nameText: '#D4AF60',
    bodyText: '#F0E8D8',
    divider: '#D4AF60',
    badgeBg: '#D4AF60',
    badgeText: '#2E1A0E',
    eventCardBg: '#F5EFE3',
    eventCardBorder: '#D4AF60',
  },
  forestModern: {
    name: 'Forest Modern',
    description: 'Clean forest green with geometric lines',
    layout: 'modern',
    headerBg: '#1A3A2A',
    bodyBg: '#1A3A2A',
    accent: '#C9A84C',
    detailsBg: '#F5F5F0',
    detailsText: '#1A2A1A',
    footerBg: '#1A3A2A',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#E0F0E0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#1A3A2A',
    eventCardBg: '#EEEDE8',
    eventCardBorder: '#C9A84C',
  },
  slateMinimal: {
    name: 'Slate Minimal',
    description: 'Cool slate gray with clean accents',
    layout: 'modern',
    headerBg: '#2A2D35',
    bodyBg: '#1E2128',
    accent: '#7A8FA6',
    detailsBg: '#F2F4F6',
    detailsText: '#2A2D35',
    footerBg: '#2A2D35',
    headerText: '#FFFFFF',
    nameText: '#7A8FA6',
    bodyText: '#D0D8E0',
    divider: '#7A8FA6',
    badgeBg: '#7A8FA6',
    badgeText: '#FFFFFF',
    eventCardBg: '#E8ECF0',
    eventCardBorder: '#7A8FA6',
  },
}

export function getInvitationTheme(key) {
  return invitationThemes[key] || invitationThemes.burgundyGold
}

export const invitationTemplates = {
  traditionalGhanaian: {
    name: 'Traditional Ghanaian',
    description: 'Three events: gathering, burial, and internment',
    icon: 'BookOpen',
    data: {
      invitationTheme: 'burgundyGold',
      title: 'FUNERAL INVITATION',
      familyAnnouncement: 'The Allied Families of the late deceased cordially invite you to the funeral and burial ceremonies of their dearly beloved. Your presence and prayers are humbly requested.',
      events: [
        { date: '', title: 'GATHERING OF FAMILY & FRIENDS', time: '', venue: '', details: '' },
        { date: '', title: 'BURIAL SERVICE', time: '', venue: '', details: '' },
        { date: '', title: 'INTERNMENT & FINAL RITES', time: '', venue: '', details: '' },
      ],
      dressCode: 'BLACK & RED',
    },
  },
  churchMemorial: {
    name: 'Church Memorial',
    description: 'Two events: memorial service and reception',
    icon: 'Church',
    data: {
      invitationTheme: 'ivoryClassic',
      title: 'MEMORIAL SERVICE INVITATION',
      familyAnnouncement: 'In the blessed hope of the resurrection, the family and church invite you to join in celebrating the life and homegoing of our beloved. Your presence will be a source of comfort.',
      events: [
        { date: '', title: 'MEMORIAL & THANKSGIVING SERVICE', time: '', venue: '', details: '' },
        { date: '', title: 'RECEPTION', time: '', venue: '', details: '' },
      ],
      dressCode: 'WHITE & GOLD',
    },
  },
  militaryService: {
    name: 'Military / Service',
    description: 'Three events: lying in state, regimental service, burial with honours',
    icon: 'Shield',
    data: {
      invitationTheme: 'forestModern',
      title: 'FUNERAL INVITATION',
      familyAnnouncement: 'The family, colleagues, and regiment invite you to the funeral and burial ceremonies of their distinguished comrade who served with honour, courage, and unwavering dedication to duty.',
      events: [
        { date: '', title: 'LYING IN STATE', time: '', venue: '', details: '' },
        { date: '', title: 'REGIMENTAL SERVICE', time: '', venue: '', details: '' },
        { date: '', title: 'BURIAL WITH FULL HONOURS', time: '', venue: '', details: '' },
      ],
      dressCode: 'BLACK & REGIMENTAL',
    },
  },
}

export const invitationDefaultData = {
  invitationTheme: 'burgundyGold',
  title: 'FUNERAL INVITATION',
  fullName: '',
  alias: '',
  age: '',
  photo: null,
  familyAnnouncement: '',
  events: [
    { date: '', title: '', time: '', venue: '', details: '' },
  ],
  rsvpPhone: '',
  location: '',
  dressCode: 'BLACK & WHITE',
  customMessage: '',
}
