export const posterThemes = {
  royalBlue: {
    name: 'Royal Blue & Gold',
    description: 'Classic, elegant blue and gold',
    headerBg: '#1a3a6e',
    bodyBg: '#1a3a6e',
    accent: '#C9A84C',
    detailsBg: '#FFFFFF',
    detailsText: '#1a1a1a',
    footerBg: '#1a3a6e',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#FFFFFF',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#1a3a6e',
  },
  midnightBlack: {
    name: 'Midnight Black & Gold',
    description: 'Regal, dramatic black and gold',
    headerBg: '#0A0A0A',
    bodyBg: '#111111',
    accent: '#C9A84C',
    detailsBg: '#1A1A1A',
    detailsText: '#E0E0E0',
    footerBg: '#0A0A0A',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#E0E0E0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#0A0A0A',
  },
  burgundyIvory: {
    name: 'Burgundy & Ivory',
    description: 'Warm, dignified burgundy and ivory',
    headerBg: '#5C1A2A',
    bodyBg: '#4A1525',
    accent: '#D4AF37',
    detailsBg: '#FDF8F0',
    detailsText: '#2A1015',
    footerBg: '#5C1A2A',
    headerText: '#FFFFFF',
    nameText: '#D4AF37',
    bodyText: '#F0E0D0',
    divider: '#D4AF37',
    badgeBg: '#D4AF37',
    badgeText: '#5C1A2A',
  },
  forestGreen: {
    name: 'Forest Green & Gold',
    description: 'Peaceful, nature-inspired green and gold',
    headerBg: '#1A3A2A',
    bodyBg: '#1A3A2A',
    accent: '#C9A84C',
    detailsBg: '#F5F5F0',
    detailsText: '#1A2A1A',
    footerBg: '#1A3A2A',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#E0F0E0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#1A3A2A',
  },
}

export function getPosterTheme(key) {
  return posterThemes[key] || posterThemes.royalBlue
}

export const posterDefaultData = {
  posterTheme: 'royalBlue',
  headerTitle: 'CALLED TO GLORY',
  fullName: '',
  alias: '',
  age: '',
  photo: null,
  dateOfDeath: '',
  placeOfDeath: '',
  announcementText: '',
  funeralArrangements: [
    { label: 'THERE WILL BE NO WAKE', value: '' },
    { label: 'BURIAL SERVICE', value: '' },
    { label: 'INTERNMENT', value: '' },
    { label: 'FINAL FUNERAL RITES', value: '' },
  ],
  father: '',
  mother: '',
  widowWidower: '',
  widowWidowerLabel: 'WIDOWER',
  children: '',
  grandchildren: '',
  siblings: '',
  inLaw: '',
  brothersSisters: '',
  cousins: '',
  nephewsNieces: '',
  chiefMourners: '',
  invitationText: 'ALL FRIENDS & SYMPATHIZERS ARE CORDIALLY INVITED',
  dressCode: 'BLACK & WHITE',
}
