export const thankYouThemes = {
  ivoryGold: {
    name: 'Ivory & Gold',
    description: 'Warm ivory with golden accents',
    layout: 'centered',
    headerBg: '#FFFFFF',
    bodyBg: '#FAF8F5',
    accent: '#8B7340',
    detailsBg: '#FFFFFF',
    detailsText: '#1A1A1A',
    footerBg: '#2A2520',
    headerText: '#2A2520',
    nameText: '#8B7340',
    bodyText: '#3A3530',
    divider: '#8B7340',
    badgeBg: '#2A2520',
    badgeText: '#FAF8F5',
    eventCardBg: '#F5F2ED',
    eventCardBorder: '#8B7340',
  },
  midnightGold: {
    name: 'Midnight & Gold',
    description: 'Dramatic black with gold flourishes',
    layout: 'centered',
    headerBg: '#0A0A0A',
    bodyBg: '#111111',
    accent: '#C9A84C',
    detailsBg: '#1A1A1A',
    detailsText: '#E0E0E0',
    footerBg: '#0A0A0A',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#E0E0E0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#0A0A0A',
    eventCardBg: 'rgba(201,168,76,0.1)',
    eventCardBorder: '#C9A84C',
  },
  burgundyCream: {
    name: 'Burgundy & Cream',
    description: 'Rich burgundy with cream warmth',
    layout: 'bordered',
    headerBg: '#5C1A2A',
    bodyBg: '#4A1525',
    accent: '#D4AF37',
    detailsBg: '#FDF8F0',
    detailsText: '#2A1015',
    footerBg: '#5C1A2A',
    headerText: '#FFFFFF',
    nameText: '#D4AF37',
    bodyText: '#F0E0D0',
    divider: '#D4AF37',
    badgeBg: '#D4AF37',
    badgeText: '#5C1A2A',
    eventCardBg: 'rgba(212,175,55,0.08)',
    eventCardBorder: '#D4AF37',
  },
  roseBlush: {
    name: 'Rose Blush',
    description: 'Soft rose and blush tones',
    layout: 'centered',
    headerBg: '#3A1020',
    bodyBg: '#4A1828',
    accent: '#D4A0A8',
    detailsBg: '#FDF0F2',
    detailsText: '#3A1020',
    footerBg: '#3A1020',
    headerText: '#FFFFFF',
    nameText: '#D4A0A8',
    bodyText: '#F8E0E5',
    divider: '#D4A0A8',
    badgeBg: '#D4A0A8',
    badgeText: '#3A1020',
    eventCardBg: 'rgba(212,160,168,0.1)',
    eventCardBorder: '#D4A0A8',
  },
  forestGreen: {
    name: 'Forest Green',
    description: 'Peaceful forest green with gold',
    layout: 'photoLeft',
    headerBg: '#0D2818',
    bodyBg: '#0A2015',
    accent: '#C9A84C',
    detailsBg: '#F0F5F0',
    detailsText: '#0D2818',
    footerBg: '#0D2818',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#D0E8D0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#0D2818',
    eventCardBg: 'rgba(201,168,76,0.08)',
    eventCardBorder: '#C9A84C',
  },
  royalNavy: {
    name: 'Royal Navy',
    description: 'Deep navy blue with golden highlights',
    layout: 'photoRight',
    headerBg: '#0E1E38',
    bodyBg: '#0A1628',
    accent: '#C9A84C',
    detailsBg: '#F0F5F8',
    detailsText: '#0A1628',
    footerBg: '#0E1E38',
    headerText: '#FFFFFF',
    nameText: '#C9A84C',
    bodyText: '#D8E8F0',
    divider: '#C9A84C',
    badgeBg: '#C9A84C',
    badgeText: '#0A1628',
    eventCardBg: 'rgba(201,168,76,0.08)',
    eventCardBorder: '#C9A84C',
  },
  purpleSilver: {
    name: 'Purple & Silver',
    description: 'Regal purple with silver accents',
    layout: 'bordered',
    headerBg: '#1E0A38',
    bodyBg: '#28104A',
    accent: '#C0C0C8',
    detailsBg: '#F5F0FA',
    detailsText: '#1E0A38',
    footerBg: '#1E0A38',
    headerText: '#FFFFFF',
    nameText: '#C0C0C8',
    bodyText: '#E8E0F0',
    divider: '#C0C0C8',
    badgeBg: '#C0C0C8',
    badgeText: '#1E0A38',
    eventCardBg: 'rgba(192,192,200,0.1)',
    eventCardBorder: '#C0C0C8',
  },
  pearlWhite: {
    name: 'Pearl White',
    description: 'Clean pearl white with warm brown',
    layout: 'minimal',
    headerBg: '#2E1A0E',
    bodyBg: '#3A2418',
    accent: '#D4AF60',
    detailsBg: '#FDF8F0',
    detailsText: '#2E1A0E',
    footerBg: '#2E1A0E',
    headerText: '#FDF8F0',
    nameText: '#D4AF60',
    bodyText: '#F0E8D8',
    divider: '#D4AF60',
    badgeBg: '#D4AF60',
    badgeText: '#2E1A0E',
    eventCardBg: '#F5EFE3',
    eventCardBorder: '#D4AF60',
  },
}

export function getThankYouTheme(key) {
  return thankYouThemes[key] || thankYouThemes.ivoryGold
}

export const thankYouTemplates = {
  traditionalThanks: {
    name: 'Traditional Thanks',
    description: 'Formal gratitude to funeral attendees',
    icon: 'BookOpen',
    data: {
      thankYouTheme: 'ivoryGold',
      thankYouMessage: 'The family of the late deceased wishes to express our heartfelt gratitude to all who supported us during this difficult time. Your prayers, presence, and kind words brought us immeasurable comfort. May God richly bless you all.',
      familySignature: 'The Allied Families',
      customClosing: 'God bless you abundantly.',
    },
  },
  churchAppreciation: {
    name: 'Church Appreciation',
    description: 'Thank you with church and pastoral focus',
    icon: 'Church',
    data: {
      thankYouTheme: 'burgundyCream',
      thankYouMessage: 'We, the family of the late deceased, wish to thank our Heavenly Father, our Pastor, the Church leadership, and the entire congregation for the outpouring of love, prayers, and support during our time of bereavement. Your ministry to our family has been a source of great strength.',
      familySignature: 'The Bereaved Family',
      customClosing: 'To God be the glory.',
    },
  },
  simpleGratitude: {
    name: 'Simple Gratitude',
    description: 'Short, heartfelt message of thanks',
    icon: 'Heart',
    data: {
      thankYouTheme: 'pearlWhite',
      thankYouMessage: 'Thank you from the bottom of our hearts for your love, support, and kindness during our time of loss. Your presence meant the world to us.',
      familySignature: 'With love, The Family',
      customClosing: 'Forever grateful.',
    },
  },
}

export const thankYouDefaultData = {
  thankYouTheme: 'ivoryGold',
  fullName: '',
  alias: '',
  photo: null,
  dateOfBirth: '',
  dateOfDeath: '',
  age: '',
  thankYouMessage: '',
  familySignature: '',
  funeralDate: '',
  customClosing: '',
}
