export const themes = {
  blackGold: {
    name: 'Black & Gold',
    description: 'Classic funeral elegance',
    pageBg: '#0A0A0A',
    secondaryBg: '#1A1A1A',
    gold: '#C9A84C',
    lightGold: '#E8D48B',
    paleGold: '#F0E6C0',
    cream: '#FAF6EE',
    offWhite: '#F5F0E8',
    heading: '#C9A84C',
    bodyText: '#FAF6EE',
    subtleText: '#E8D48B',
    border: '#C9A84C',
    accent: '#B8960F',
    placeholderBg: '#2A2520',
  },
  whiteNavy: {
    name: 'White & Navy Blue',
    description: 'Elegant and refined',
    pageBg: '#FFFFFF',
    secondaryBg: '#F8F9FC',
    gold: '#8C8C8C',
    lightGold: '#B0B0B0',
    paleGold: '#E0E0E0',
    cream: '#2C3E6B',
    offWhite: '#1A2A4A',
    heading: '#1A2A4A',
    bodyText: '#2C3E6B',
    subtleText: '#5A6A8A',
    border: '#8C8C8C',
    accent: '#C0C0C0',
    placeholderBg: '#EEF0F5',
  },
  burgundyCream: {
    name: 'Burgundy & Cream',
    description: 'Warm and dignified',
    pageBg: '#FDF8F0',
    secondaryBg: '#F5EDE0',
    gold: '#C9A84C',
    lightGold: '#D4B86A',
    paleGold: '#E8D48B',
    cream: '#4A1A2A',
    offWhite: '#3A0A1A',
    heading: '#6B1A2A',
    bodyText: '#4A1A2A',
    subtleText: '#7A3A4A',
    border: '#C9A84C',
    accent: '#8B1A2A',
    placeholderBg: '#F0E8DD',
  },
}

export function getTheme(themeKey) {
  return themes[themeKey] || themes.blackGold
}
